# Generated by Django 5.2.6 on 2025-09-29 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smuser',
            name='image',
            field=models.ImageField(default=2, upload_to='images/'),
            preserve_default=False,
        ),
    ]
